=== llmandres/WsLMSGI/15_ExpresionesRegularesRestricciones/XSD14.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="ciudad">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="nombre_ciudad">
                <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="([A-Z])[a-z]{3,20}"/>
                                </xs:restriction>
                            </xs:simpleType>
            </xs:element>
            <xs:element name="poblacion">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minExclusive value="100"></xs:minExclusive>
                        <xs:maxExclusive value="100000"></xs:maxExclusive>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="alcalde">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nombre">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="[A-Z][a-z]{1,9}"></xs:pattern>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="apellidos">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="[a-zA-Z]+\s[a-zA-Z]+"></xs:pattern>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="telefono">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:pattern value="\+34\d{9}"></xs:pattern>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="tarjeta_credito"></xs:element>
                        <xs:element name="correo_electronico">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="[a-zA-Z0-9_]+([.][a-zA-Z0-9_]+)*@[a-zA-Z0-9_]+([.][a-zA-Z0-9_]+)*[.][a-zA-Z]{2,5}"></xs:pattern>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="edad">
                        <xs:simpleType>
                            <xs:restriction base="xs:integer"> 
                                <xs:minExclusive value="18"></xs:minExclusive>
                                <xs:maxExclusive value="120"></xs:maxExclusive>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:complexType>
            </xs:element>
            <xs:element name="funcionarios">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="funcionario" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="nombre_apellidos_funcionario">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="([a-zA-Z]+\s[a-zA-Z]+){1,50}"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                    <xs:element name="codigo_postal">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:integer">
                                                <xs:pattern value="\d{5}"></xs:pattern>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                    <xs:element name="fecha_nacimiento">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="\d{2}/\d{2}/\d{4}"></xs:pattern>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                    <xs:element name="contrasenia">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="[A-Z](\d{2})+[$@!%].{6,}"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                    <xs:element name="cuenta_bancaria">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="ES\d{4}\s\d{4}\s\d{4}"></xs:pattern>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                </xs:sequence>
                                <xs:attribute name="id">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:pattern value="[a-zA-Z0-9]{1,10}"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
          
        </xs:sequence>
        <xs:attribute name="codigo_identificador">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[^\d]{2}-\d{2,5}"/>
                </xs:restriction>
            </xs:simpleType>

        </xs:attribute>
    </xs:complexType>

</xs:element>
</xs:schema>

=== llmandres/WsLMSGI/15_ExpresionesRegularesRestricciones/XSD14.xml
<?xml version="1.0" encoding="UTF-8"?>
<ciudad codigo_identificador="BB-232" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:noNamespaceSchemaLocation= "XSD14.xsd">
    <nombre_ciudad>Barcelona</nombre_ciudad>
    <poblacion>500</poblacion>
    <alcalde edad="45">
      <nombre>Carlos</nombre>
      <apellidos>Gonzalez Perez</apellidos>
      <telefono>+34661435678</telefono>
      <tarjeta_credito>1234 5678 9012 3456</tarjeta_credito>
      <correo_electronico>carlos@example.com</correo_electronico>
    </alcalde>
    <funcionarios>
      <funcionario id="F001">
        <nombre_apellidos_funcionario>Juan Martinez</nombre_apellidos_funcionario>
        <codigo_postal>08001</codigo_postal>
        <fecha_nacimiento>15/03/1980</fecha_nacimiento>
        <contrasenia>A21@232323d</contrasenia>
        <cuenta_bancaria>ES1234 5678 9012</cuenta_bancaria>
      </funcionario>
      <funcionario id="F002">
        <nombre_apellidos_funcionario>Maria Lopez</nombre_apellidos_funcionario>
        <codigo_postal>08002</codigo_postal>
        <fecha_nacimiento>20/05/1985</fecha_nacimiento>
        <contrasenia>X32@2gfz3d</contrasenia>
        <cuenta_bancaria>ES5678 9012 3456</cuenta_bancaria>
      </funcionario>
      </funcionarios>
  </ciudad>
