=== llmandres/WsLMSGI/13_DTDyXSD/CodificarPunto4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="empresa">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"></xs:element>
            <xs:element name="NIF" type="xs:string"></xs:element>
            <xs:element name="espaniola" type="xs:boolean"></xs:element>
            <xs:element name="capitalSocial" type="xs:double"></xs:element>
            <xs:element name="direccion">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="tipoVia" type="xs:string"></xs:element>
                        <xs:element name="nombreVia" type="xs:string"></xs:element>
                        <xs:element name="CP" type="xs:string"></xs:element>
                        <xs:element name="pais" type="xs:string"></xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="empleados">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="empleado" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="nombre" type="xs:string"></xs:element>
                                    <xs:element name="apellidos" type="xs:string" minOccurs="2" maxOccurs="unbounded"></xs:element>
                                    <xs:element name="DNI" type="xs:string"></xs:element>
                                    <xs:element name="extranjero"></xs:element>
                                    <xs:element name="fechaNacimiento" type="xs:date"></xs:element>
                                    <xs:element name="salario" type="xs:double"></xs:element>
                                    <xs:element name="direccion" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:all>
                                                <xs:element name="direccion_empleado" type="xs:string"></xs:element>
                                                <xs:element name="pais" type="xs:string"></xs:element>
                                            </xs:all>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="casado" type="xs:boolean"></xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== llmandres/WsLMSGI/13_DTDyXSD/XSDCodificar_XMLPunto4.xml
<?xml version="1.0" encoding="UTF-8"?>
<empresa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:noNamespaceSchemaLocation= "CodificarPunto4.xsd">
    <nombre>Mi Empresa</nombre>
    <NIF>12345678A</NIF>
    <espaniola>true</espaniola>
    <capitalSocial>100000.00</capitalSocial>
    <direccion>
        <tipoVia>Calle</tipoVia>
        <nombreVia>Gran Vía</nombreVia>
        <CP>28001</CP>
        <pais>ESPAÑA</pais>
    </direccion>
    <empleados>
        <empleado>
            <nombre>Juan</nombre>
            <apellidos>Pérez Gómez</apellidos>
            <DNI>12345678B</DNI>
            <extranjero>false</extranjero>
            <fechaNacimiento>1990-01-01</fechaNacimiento>
            <salario>50000.00</salario>
            <direccion>
                <direccion_empleado>Calle Gran Vía 67, Madrid</direccion_empleado>
                <pais>ESPAÑA</pais>
            </direccion>
            <casado>true</casado>
        </empleado>
        <empleado>
            <nombre>Maria</nombre>
            <apellidos>Ruiz López</apellidos>
            <DNI>98765432C</DNI>
            <extranjero>true</extranjero>
            <fechaNacimiento>1985-05-15</fechaNacimiento>
            <salario>60000.00</salario>
            <direccion>
                <pais>ESPAÑA</pais>
                <direccion_empleado>Av. Diagonal 123, Barcelona</direccion_empleado>
            </direccion>
            <casado>false</casado>
        </empleado>
    </empleados>
</empresa>
